language :
- python

python : 
- "3.7-dev"

#command to install dependencies
install:
- pip install -r requirements.txt
- pip install nose


#run tests
Scripts :
- pytest --cov-report term-missing --cov=app

after_success:
- coveralls